


---

Introduction to the Tidyverse

```{r}
library(gapminder)
library(dplyr)

gapminder
```
Filtering and arranging

```{r}

gapminder %>%
	#es la funcion que indica a R que va a manipular la informacion
	filter(year==1957)
	
	#la libreria dplyr es la que permite utilizar "filter"
	
	#ordenar de forma ascendente la columna indicada
	arrange(lifeExp)
	
	#si se quiere ordenar de forma descendente: desc
	arrange(desc(lifeExp))
	
	
	arrange(desc(pop))
	
	
	
```


The verb mutate
```{r}

#modificar la columna
gapminder %>%
	mutate(lifeExp = 12*lifeExp)

#añadir nueva columna calculada	
gapminder %>%
	mutate(lifeExpMonths = 12*lifeExp)

```
combining filter, mutate and arrange
```{r}
gapminder %>%
	filter(year==2007) %>%
	mutate(lifeExpMonths = 12*lifeExp) %>%
	arrange(desc(lifeExpMonths))
	

```

```{r}
library(ggplot2)

gapminder_1952 <- gapminder %>%
	filter(year==1952)
	
# ejemplo para dos criterios
# filter(year==1952, continent=="Asia")
# 
# filter(year==1952 | continent=="Asia")

#tambien
#filter(year==1952) %>%
#filter(continent=="Asia")

gapminder_1952

#la funcion recibe el set de datos. https://ggplot2.tidyverse.org/reference/ggplot.html
#Aesthetic mappings describe how variables in the data are mapped to visual properties (aesthetics) of geoms. 
#Aesthetic mappings can be set in ggplot() and in individual layers.

ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + geom_point()

	
```
log scaling
```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + 
geom_point() + 
scale_x_log10() + 
scale_y_log10()
 

```

```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) + 
	geom_point() + 
	scale_x_log10() + 
	scale_y_log10()
#asigna un color para cada clasificacion especificada

```


```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) +
  geom_point() +
  scale_x_log10()

```